# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

#version: '3.4'

services:
  eshopdb:
    image: postgres
    container_name: eshopdb

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data

  distributedCache:
    image: redis
    container_name: cache
    restart: always
    ports:
     - 6379:6379


  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
       - ACCEPT_EULA=Y
    restart: always
    ports:
      - 5341:80
      - 9092:80

    
